public enum SentenceKey
{
    NONE,
    DOOR_BUTTON,
    ARMORY,
    CRATE,
    TRAPDOOR,
    SCREW,
    OTHER_MAN,
    COMPUTER,
    WINDOW,
    SCREWDRIVER_BEFORE,
    FLASHLIGHT_BEFORE,
    CARD_BEFORE,
    SCREWDRIVER_AFTER,
    FLASHLIGHT_AFTER,
    CARD_AFTER
}